name: SMA Battery Controller
version: 0.0.20
slug: sma_battery_controller
description: Control SMA Sunny Tripower SE 10 inverter over Modbus via MQTT
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
options:
  mqtt_server_address: 127.0.0.1
  mqtt_server_port: 1883
  mqtt_user: ""
  mqtt_password: ""
  sma_inverter_modbus_address: 192.168.1.100
  sma_inverter_modbus_port: 502
  maximum_battery_control: 5000
  debug_enabled: true
  modbus_interval_in_seconds: 5
  reset_interval_minutes: 5
  device_id: sma_battery_controller
  post_command_delay_ms: 1600
schema:
  mqtt_server_address: str
  mqtt_server_port: int
  mqtt_user: str
  mqtt_password: str
  sma_inverter_modbus_address: str
  sma_inverter_modbus_port: int
  maximum_battery_control: int
  debug_enabled: bool
  modbus_interval_in_seconds: int
  reset_interval_minutes: int
  device_id: str
  post_command_delay_ms: int